excavator:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  excavation_slope_controller:
    type: position_controllers/JointPositionController
    joint: excavation_slope_control_joint

  excavation_1st_translation_controller:
    type: position_controllers/JointPositionController
    joint: excavation_1st_translation_joint

  excavation_2nd_translation_controller:
    type: position_controllers/JointPositionController
    joint: excavation_2nd_translation_joint

  excavation_arm_translation_controller:
    type: position_controllers/JointPositionController
    joint: excavation_arm_translation_joint
  
  excavation_arm_controller:
    type: effort_controllers/JointVelocityController
    joint: excavation_arm_control_joint
    pid: {p: 22, i: 0, d: 5, i_clamp_max: 1}

  scooper_controller:
    type: effort_controllers/JointPositionController
    joint: scooper_control_joint
    pid: {p: 3, i: 0, d: 1, i_clamp_max: 1}

  gazebo_ros_control/pid_gains:
    excavation_slope_control_joint: {p: 30000.0, i: 0.0, d: 10000.0}
    excavation_1st_translation_joint: {p: 30000.0, i: 0.0, d: 10000.0}
    excavation_2nd_translation_joint: {p: 30000.0, i: 0.0, d: 10000.0}
    excavation_arm_translation_joint: {p: 30000.0, i: 0.0, d: 10000.0}
